### ISSUE TITLE
I could not build the C# babelfish driver using the instructions on repository

### ISSUE THREAD

**Issue by deepakorantak** [bblfsh/csharp-driver#1]
When I try to setup the build environment using following command - 
root@ip-172-31-34-50:~/sourced/git/csharp-driver# bblfsh-sdk update
managed file ".travis.yml" has changed, discarding changes
managed file "driver/normalizer/transforms.go" has changed, discarding changes
creating file ".git/hooks/pre-commit"

Please suggest the resolution

**Comment by dennwc** [comment]
@deepakorantak Sorry, the driver is in deep alpha and is not yet complete. But it's on our roadmap to finish in the following 2-3 months.
