### ISSUE TITLE
No drivers in DockerHub

### ISSUE THREAD

**Issue by rporres** [bblfsh/csharp-driver#13]
https://hub.docker.com/r/bblfsh/csharp-driver/tags is empty :(

**Comment by dennwc** [comment]
I guess it needs a deploy token configured on Travis.

**Comment by dennwc** [comment]
And we haven't pushed any releases yet. Will do it later today.

**Comment by dennwc** [comment]
Not sure how it passes, but we definitely need a token on CI:
https://travis-ci.org/bblfsh/csharp-driver/builds/482583598#L511

**Comment by meyskens** [comment]
Fixed this! Closing this issue.
