### ISSUE TITLE
Driver does not support comments

### ISSUE THREAD

**Issue by dennwc** [bblfsh/csharp-driver#3]
The current implementation does not produce any comments in the native AST. Should find a flag to enable it.

**Comment by dennwc** [comment]
It seems like comments are represented by `SyntaxTrivia` that only contain positions, so we will need to extract the comment text separately.

**Comment by creachadair** [comment]
I think this is an important modelling problem that we should probably discuss before we commit to an implementation. As you pointed out, there are some tradeoffs, and it will make sense to think about how those affect the various languages. 

In a sense this is similar in spirit to the problem with location: Different compilers represent location differently, and thus the "convenient" representation in a language-agnostic structure is often more work than the native representation the compiler chose. So too with comments, which are attached in various ways for internal design reasons. If we want to pick a single representation—or perhaps a couple of reusable variations—we should do it deliberately.
