### ISSUE TITLE
Parsing a file rise a panic

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/csharp-driver#32]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470045137

might be related to https://github.com/bblfsh/csharp-driver/issues/27
causes https://github.com/bblfsh/bblfshd/issues/259

While using `bblfsh/bblfshd:v2.11.8` image (the current latest), and parsing a `csharp` file I discovered that it screwed the bblfsh container up, and it won't be able to accept new parse requests.

here is how to reproduce the bug:

```shell
$ docker run --rm -d --name bblfshd --privileged -p 9999:9432 bblfsh/bblfshd:v2.11.8

$ docker exec -it bblfshd bblfshctl driver list
+----------+-------+---------+--------+---------+----+----+--------+
| LANGUAGE | IMAGE | VERSION | STATUS | CREATED | OS | GO | NATIVE |
+----------+-------+---------+--------+---------+----+----+--------+
+----------+-------+---------+--------+---------+----+----+--------+
Response time 24.026µs

$ docker exec -it bblfshd bblfshctl driver install csharp bblfsh/csharp-driver
Installing csharp language driver from "bblfsh/csharp-driver"... Done

$ docker exec -it bblfshd bblfshctl driver list
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
| LANGUAGE |             IMAGE             | VERSION | STATUS | CREATED | OS |  GO  |            NATIVE            |
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
| ...                                                                                                              |
| csharp   | docker://bblfsh/csharp-driver | v1.4.0  | beta   | 2 weeks |    | 1.10 | microsoft/dotnet:2.1-runtime |
| ...                                                                                                              |
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
Response time 337.109µs

# Parsing CS files will fail
$ docker exec -it bblfshd bblfshctl parse /example.cs

# the command takes forever with no output, so let's stop it
CTRL+C

# is there something in the container logs?
$ docker logs -f bblfshd
time="2019-03-06T07:05:12Z" level=info msg="bblfshd version: v2.11.8 (build: 2019-02-22T17:20:08+0000)"
time="2019-03-06T07:05:12Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2019-03-06T07:05:12Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2019-03-06T07:05:12Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2019-03-06T07:08:57Z" level=info msg="driver csharp installed "bblfsh/csharp-driver:latest""
panic: invalid tracer configuration: lookup localhost on 1.1.1.1:53: no such host

goroutine 1 [running]:
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.RunNative(0xba9260, 0xc4200a0180, 0xb139e9, 0x6, 0xc420339ad0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:35 +0x162
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.Run(0xb139e9, 0x6, 0xc420339ad0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, 0xc42039d5e0, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:20 +0x74
main.main()
	/go/src/github.com/bblfsh/csharp-driver/driver/main.go:11 +0x5a
```

:point_down: Here is the offending file [examples/example.cs](https://github.com/dpordomingo/empathy-sessions/blob/master/4-engine/examples/example.cs) (but it also happened with many others)
<details><pre>
// A Hello World! program in C#.
using System;
namespace HelloWorld
{
    class Hello 
    {
        static void Main() 
        {
            Console.WriteLine("Hello World!");

            // Keep the console window open in debug mode.
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}
</pre></details>

**Comment by bzz** [comment]
@dpordomingo thank you for such detailed report!

BTW do you know that the best way to make sure whether it's a driver misbehaves and verify the bug is to start only the driver and talk directly to it with the client? It speaks the same protocol as bblfshd, so no modifications are required. I find this trick very helpful in order to reduce the "impact surface" while reproducing the issues.

Here is what I did:
```
docker run --rm -it -p 9432:9432 bblfsh/csharp-driver:v1.4.0 --log-level=debug
wget https://raw.githubusercontent.com/dpordomingo/empathy-sessions/master/4-engine/examples/example.cs
bblfsh-cli example.cs
```

And, as expected, this produces the semantic UAST.

This most probably means that it has to do with `bblfshd` and https://github.com/bblfsh/bblfshd/issues/259 more, rather then C# driver but @dennwc would be able to tell better.

**Comment by dpordomingo** [comment]
wow, I didn't know any of these tricks!
Many thanks @bzz !

I tried it too, and it does not fail, so I assume it is only a problem on `bblfshd` so this could be also closed.

**Comment by dennwc** [comment]
Not related to C#, the error comes from Jaeger client:
```
panic: invalid tracer configuration: lookup localhost on 1.1.1.1:53: no such host
```
Not sure why it tries to resolve `localhost` with DNS, but I cannot reproduce this in any way I tried.

@dpordomingo If this problem persists, check if you set any Jaeger-related config vars when running `bblfshd`.
