### ISSUE TITLE
Missing OS column val in the driver list table

### ISSUE THREAD

**Issue by bzz** [bblfsh/csharp-driver#36]
A nitpick on the driver manifest most probably, but right now it looks like:
```
$ bblfshctl driver list
+------------+------------------------------------------+---------+--------+---------+--------+-------------+------------------------------+
|  LANGUAGE  |                  IMAGE                   | VERSION | STATUS | CREATED |   OS   |     GO      |            NATIVE            |
+------------+------------------------------------------+---------+--------+---------+--------+-------------+------------------------------+
| python     | docker://bblfsh/python-driver:latest     | v2.8.2  | beta   | 2 days  | alpine | 1.10-alpine | python:3.6-alpine            |
| csharp     | docker://bblfsh/csharp-driver:latest     | v1.4.1  | beta   | 6 days  |        | 1.10        | microsoft/dotnet:2.1-runtime |
```

Found while looking at https://github.com/bblfsh/bblfshd/issues/270

**Comment by creachadair** [comment]
The "OS" field appears to be populated from the manifest, which I think is intended to be read from `manifest.toml`. But I have not yet figured out where that gets written in our build process.

**Comment by dennwc** [comment]
This field is unused, to be honest. The new build system ignores it so it has no effect.

**Comment by creachadair** [comment]
> This field is unused, to be honest. The new build system ignores it so it has no effect.

Should we drop the field entirely then? I suspect that will actually be more work, but if it's not really adding any value I'd be game to do that and reduce visual noise for the user.

**Comment by dennwc** [comment]
Opened an issue: https://github.com/bblfsh/bblfshd/issues/272
